# Generated by Django 4.1.2 on 2023-01-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetShopApp', '0004_productosaves'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosHansterArdillas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('precio', models.CharField(max_length=10)),
                ('imagen', models.ImageField(upload_to='Fotos')),
            ],
            options={
                'verbose_name': 'ProductosHansterArdillas',
            },
        ),
    ]
